const INPUT_DATA = [
  {
    id: 'organization',
    type: 'text',
    name: 'Податковий номер',
    placeholder: 'Податковий номер',
    required: false,
    value: '',
    isRequired: false,
    isHidePlaceholder: false,
  },
  {
    id: 'role',
    type: 'text',
    name: 'Посада',
    placeholder: 'Посада',
    required: false,
    value: '',
    isRequired: false,
    isHidePlaceholder: false,
  },
  {
    id: 'fullName',
    type: 'text',
    name: 'ПІБ',
    placeholder: 'ПІБ',
    required: true,
    value: '',
    isRequired: false,
    isHidePlaceholder: false,
  },
  {
    id: 'phone',
    type: 'tel',
    name: 'Номер телефону',
    placeholder: 'Номер телефону',
    required: true,
    value: '',
    isRequired: false,
    isHidePlaceholder: false,
  },
  {
    id: 'email',
    type: 'email',
    name: 'Email',
    placeholder: 'Email',
    required: true,
    value: '',
    isRequired: false,
    isHidePlaceholder: false,
  },
];

export default INPUT_DATA;
